language: php

sudo: false

php:
  - 7.3

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:^3.3'"
  - sh -c "composer require 'squizlabs/php_codesniffer:^3.5'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config"

notifications:
  email: false
